

"""导出 llm_caibao 数据库全部表结构与数据到本地 .sql 文件 (pg_dump plain 风格)。

用法:
  python scripts/dump_db.py                          # 导出全部表到 backups/llm_caibao_<时间戳>.sql
  python scripts/dump_db.py --out /path/dump.sql     # 指定输出文件
  python scripts/dump_db.py --table red_low_vol      # 只导出指定表 (可多次)
  python scripts/dump_db.py --table red_low_vol --table my_stocks
  python scripts/dump_db.py --schema-only            # 只导出表结构 (不含数据)
  python scripts/dump_db.py --data-only              # 只导出数据 (不含表结构, 需目标已有表)

说明:
  - 动态枚举 public schema 下全部用户表, 无需维护表名单, 新表自动包含
  - 输出内容: CREATE TABLE(列+主键/唯一/检查约束) + 非约束索引 + COPY 数据 + 序列 setval
  - 外键约束统一追加在文件末尾, 避免表创建顺序问题
  - 数据用 COPY 格式 (pg_dump 同款), 可直接 psql -f 导入, 也可用 scripts/restore_db.py
  - 连接串从根目录 .env 的 DATABASE_URL 读取 (同 api.pg_service)
"""
from __future__ import annotations

import argparse
import io
import re
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from api import pg_service  # noqa: E402

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# 匹配 serial/identity 列的 nextval 默认值: nextval('public.xxx_id_seq'::regclass)
_SERIAL_RE = re.compile(r"^nextval\('([^']+)'::regclass\)$")

_SERIAL_TYPES = {
    "smallint": "SMALLSERIAL",
    "integer": "SERIAL",
    "bigint": "BIGSERIAL",
}


async def _list_tables(conn) -> list[str]:
    """public schema 下所有用户表 (按名称排序)。"""
    rows = await conn.fetch(
        "SELECT table_name FROM information_schema.tables "
        "WHERE table_schema = 'public' AND table_type = 'BASE TABLE' ORDER BY table_name;"
    )
    return [r[0] for r in rows]


async def _table_columns(conn, table: str) -> list[dict]:
    """获取列定义: 名称/精确类型/NOT NULL/默认值(含 nextval 解析)/自增属性。"""
    rows = await conn.fetch(
        """
        SELECT a.attname,
               format_type(a.atttypid, a.atttypmod) AS data_type,
               a.attnotnull,
               pg_get_expr(d.adbin, d.adrelid) AS default_expr,
               a.attidentity
        FROM pg_attribute a
        LEFT JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
        WHERE a.attrelid = $1::regclass AND a.attnum > 0 AND NOT a.attisdropped
        ORDER BY a.attnum;
        """,
        f"public.{table}",
    )
    return [
        {
            "name": r[0],
            "type": r[1],
            "notnull": r[2],
            "default": r[3],
            "identity": r[4],
        }
        for r in rows
    ]


def _serial_seq(col: dict, table: str) -> str | None:
    """若列为标准 serial (nextval 且序列名=表_列_seq, 整数类型), 返回序列名, 否则 None。"""
    if col["identity"] in ("a", "d") or not col["default"]:
        return None
    if col["type"] not in _SERIAL_TYPES:
        return None
    m = _SERIAL_RE.match(col["default"])
    if not m:
        return None
    seq_full = m.group(1)
    if seq_full.rsplit(".", 1)[-1] == f"{table}_{col['name']}_seq":
        return seq_full
    return None


def _col_def(col: dict, table: str) -> str:
    """单列 DDL (serial 列用 SERIAL/BIGSERIAL 简写, 自动建序列)。"""
    parts = [f'"{col["name"]}"']
    seq = _serial_seq(col, table)
    if seq is not None:
        parts.append(_SERIAL_TYPES[col["type"]])
    else:
        parts.append(col["type"])
        if col["identity"] == "a":
            parts.append("GENERATED ALWAYS AS IDENTITY")
        elif col["identity"] == "d":
            parts.append("GENERATED BY DEFAULT AS IDENTITY")
        elif col["default"]:
            parts.append(f"DEFAULT {col['default']}")
    if col["notnull"]:
        parts.append("NOT NULL")
    return " ".join(parts)


async def _table_constraints(conn, table: str) -> list[tuple[str, str]]:
    """主键/唯一/检查约束 (contype p/u/c), 返回 [(conname, constraintdef)]。"""
    rows = await conn.fetch(
        """
        SELECT conname, pg_get_constraintdef(oid)
        FROM pg_constraint
        WHERE conrelid = $1::regclass AND contype IN ('p', 'u', 'c')
        ORDER BY contype, conname;
        """,
        f"public.{table}",
    )
    return [(r[0], r[1]) for r in rows]


async def _foreign_keys(conn, table: str) -> list[tuple[str, str]]:
    """外键约束 (contype f), 返回 [(conname, constraintdef)]。"""
    rows = await conn.fetch(
        """
        SELECT conname, pg_get_constraintdef(oid)
        FROM pg_constraint
        WHERE conrelid = $1::regclass AND contype = 'f'
        ORDER BY conname;
        """,
        f"public.{table}",
    )
    return [(r[0], r[1]) for r in rows]


async def _table_indexes(conn, table: str) -> list[str]:
    """非约束索引 (排除主键/唯一约束自动建的索引), 返回完整 indexdef。"""
    rows = await conn.fetch(
        """
        SELECT pg_get_indexdef(idx.indexrelid)
        FROM pg_index idx
        JOIN pg_class i ON i.oid = idx.indexrelid
        JOIN pg_class t ON t.oid = idx.indrelid
        JOIN pg_namespace n ON n.oid = t.relnamespace
        WHERE n.nspname = 'public' AND t.relname = $1
          AND NOT idx.indisprimary
          AND NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conindid = idx.indexrelid)
        ORDER BY i.relname;
        """,
        table,
    )
    return [r[0] for r in rows]


def _write_table_ddl(out, table: str, cols: list[dict],
                     constraints: list[tuple[str, str]]) -> None:
    """写 CREATE TABLE (含主键/唯一/检查约束)。"""
    out.write(f"CREATE TABLE public.{table} (\n")
    col_lines = [_col_def(c, table) for c in cols]
    for cname, cdef in constraints:
        col_lines.append(f"CONSTRAINT {cname} {cdef}")
    out.write(",\n".join("    " + ln for ln in col_lines))
    out.write("\n);\n\n")


def _write_indexes(out, table: str, indexes: list[str]) -> None:
    for idx in indexes:
        # indexdef 形如 "CREATE INDEX xxx ON public.tab ...", 保持原样
        out.write(f"{idx};\n")
    if indexes:
        out.write("\n")


async def _write_copy_data(conn, out, table: str, cols: list[dict]) -> int:
    """写 COPY 数据块, 返回导出行数。"""
    col_names = ", ".join(f'"{c["name"]}"' for c in cols)
    out.write(f"COPY public.{table} ({col_names}) FROM stdin;\n")
    buf = io.BytesIO()
    # asyncpg copy_from_query 会包装成 COPY (<query>) TO STDOUT, 传 SELECT 即可
    await conn.copy_from_query(f"SELECT {col_names} FROM public.{table}", output=buf)
    data = buf.getvalue().decode("utf-8")
    out.write(data)
    out.write("\\.\n\n")
    # COPY text 格式: N 行数据 = N 个换行 (无表头)
    return data.count("\n")


def _write_seq_reset(out, table: str, cols: list[dict]) -> None:
    """把自增序列设为 max(自增列)+1, 保证导入后新插入 id 不冲突。"""
    for c in cols:
        seq = _serial_seq(c, table)
        if seq is None:
            continue
        col = c["name"]
        # 序列名含 schema 时保留 (如 public.xxx_id_seq), 无 schema 则补 public.
        if "." not in seq:
            seq = f"public.{seq}"
        out.write(
            f"SELECT setval('{seq}', "
            f"COALESCE((SELECT max({col}) FROM public.{table}), 0) + 1, false);\n"
        )
    if any(_serial_seq(c, table) for c in cols):
        out.write("\n")


async def dump_database(conn, tables: list[str] | None, out_path: Path,
                        schema_only: bool = False, data_only: bool = False) -> None:
    """导出到 out_path, 返回 None (行数打印由调用方处理)。"""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    all_tables = await _list_tables(conn)
    tables = tables or all_tables
    missing = [t for t in tables if t not in all_tables]
    if missing:
        raise RuntimeError(f"表不存在: {', '.join(missing)}; 可用: {', '.join(all_tables)}")

    fk_all: list[tuple[str, str, str]] = []  # (table, conname, constraintdef)
    with out_path.open("w", encoding="utf-8") as out:
        out.write(f"-- llm_caibao 数据库导出\n")
        out.write(f"-- 时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        out.write(f"-- 表: {', '.join(tables)}\n")
        out.write("-- 可用 psql -f 或 scripts/restore_db.py 导入\n\n")
        out.write("BEGIN;\n\n")

        for table in tables:
            cols = await _table_columns(conn, table)
            if not cols:
                print(f"跳过 {table}: 表不存在或无列")
                continue

            if not data_only:
                constraints = await _table_constraints(conn, table)
                _write_table_ddl(out, table, cols, constraints)
                _write_indexes(out, table, await _table_indexes(conn, table))
                fk_all.extend((table, n, d) for n, d in await _foreign_keys(conn, table))

            if not schema_only:
                n = await _write_copy_data(conn, out, table, cols)
                _write_seq_reset(out, table, cols)
                print(f"导出 {table}: {n} 行")

        # 外键统一放最后 (避免跨表创建顺序问题)
        if fk_all and not data_only:
            out.write("-- 外键约束\n")
            for table, cname, cdef in fk_all:
                out.write(f"ALTER TABLE public.{table} ADD CONSTRAINT {cname} {cdef};\n")
            out.write("\n")

        out.write("COMMIT;\n")
    print(f"已写出: {out_path} ({out_path.stat().st_size / 1024:.1f} KB)")


async def main() -> None:
    parser = argparse.ArgumentParser(description="导出 llm_caibao 全部表结构与数据到 .sql")
    parser.add_argument("--out", default="", help="输出文件 (默认 backups/llm_caibao_<时间戳>.sql)")
    parser.add_argument("--table", action="append", default=[], help="只导出指定表 (可多次)")
    parser.add_argument("--schema-only", action="store_true", help="只导出表结构")
    parser.add_argument("--data-only", action="store_true", help="只导出数据")
    args = parser.parse_args()

    if args.schema_only and args.data_only:
        parser.error("--schema-only 与 --data-only 不能同时使用")

    out = Path(args.out) if args.out else (
        PROJECT_ROOT / "backups" / f"llm_caibao_{datetime.now().strftime('%Y%m%d_%H%M%S')}.sql"
    )

    pool = await pg_service._get_pool()
    async with pool.acquire() as conn:
        await dump_database(conn, args.table or None, out,
                            schema_only=args.schema_only, data_only=args.data_only)


if __name__ == "__main__":
    import asyncio
    asyncio.run(main())
